"""Tests for shared camera config normalization."""

import os
import sys
import types

import pytest

# Path setup
_CARM_DEPLOY_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _CARM_DEPLOY_ROOT not in sys.path:
    sys.path.insert(0, _CARM_DEPLOY_ROOT)

if "rospy" not in sys.modules:
    _rospy_mock = types.ModuleType("rospy")
    _rospy_mock.logwarn = lambda *a, **kw: None
    sys.modules["rospy"] = _rospy_mock

from core.camera_config import DEFAULT_CAMERA_TOPICS, DEFAULT_SYNC_SLOP, resolve_camera_config


class TestResolveCameraConfig:
    def test_default_camera_topics(self):
        cfg = resolve_camera_config({})
        assert cfg.topics == DEFAULT_CAMERA_TOPICS

    def test_default_sync_slop(self):
        cfg = resolve_camera_config({})
        assert cfg.sync_slop_sec == DEFAULT_SYNC_SLOP

    def test_camera_topics_string(self):
        cfg = resolve_camera_config({'camera_topics': '/cam1,/cam2'})
        assert cfg.topics == ['/cam1', '/cam2']

    def test_camera_topics_list(self):
        cfg = resolve_camera_config({'camera_topics': ['/cam1']})
        assert cfg.topics == ['/cam1']

    def test_camera_names_autogenerated(self):
        cfg = resolve_camera_config({'camera_topics': ['/wrist/color/image_raw']})
        assert cfg.names == ['wrist_color_image_raw']
        assert cfg.primary_name == 'wrist_color_image_raw'

    def test_invalid_primary_falls_back(self):
        cfg = resolve_camera_config(
            {'camera_topics': ['/cam1'], 'camera_names': ['wrist'], 'primary_camera': 'third'}
        )
        assert cfg.primary_name == 'wrist'

    def test_sync_slop_positive(self):
        with pytest.raises(ValueError):
            resolve_camera_config({'sync_slop': -1})
